name: one_percent_improve
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  firebase_storage: ^13.0.5
  url_launcher: ^6.3.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  shared_preferences: ^2.5.4
  random_string: ^2.3.1
  device_preview: ^1.3.1
  google_sign_in: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  video_player: ^2.8.1
  flutter_native_splash: ^2.4.7
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/playstore.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- CRITICAL: YOU MUST REGISTER YOUR ASSETS HERE ---
  assets:
    - assets/Lifestyle of when weighing gym.json
    - assets/app_logo.png
    - assets/playstore.png


  fonts:
    - family: Poppins-extra
      fonts:
        - asset: fonts/poppins.extrabold.ttf
    - family: Poppins-semi
      fonts:
        - asset: fonts/poppins.semibold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Voegies.ttf
    - family: bbr
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: intr
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf

# --- NATIVE SPLASH CONFIGURATION ---
# ... (rest of your pubspec.yaml above)

# --- NATIVE SPLASH CONFIGURATION ---
flutter_native_splash:
  color: "#000000"
  image: assets/playstore.png
  color_dark: "#000000"
  image_dark: assets/playstore.png

  android_12:
    image: assets/playstore.png
    icon_background_color: "#000000"
    image_dark: assets/playstore.png
    icon_background_color_dark: "#000000"

  # Controls how the image is placed on older devices
  android_gravity: center
  ios_content_mode: center